[package]
name = "good-ormning"
version = "0.1.4"
edition = "2021"
license = "ISC"
description = "Maybe an ORM"
homepage = "https://github.com/andrewbaxter/good-ormning"
repository = "https://github.com/andrewbaxter/good-ormning"
readme = "readme.md"

[dependencies]
chrono = "0.4.23"
enum_dispatch = "0.3.9"
genemichaels = "0.1.15"
hex = "0.4.3"
proc-macro2 = "1.0.49"
quote = "1.0.23"
rpds = "0.12.0"
samevariant = "0.0.1"
stable-hash = "0.4.3"
syn = "1.0.107"

[workspace]
members = ["integration_tests"]
