[package]
name = "goodormning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.9"
petgraph = "0.6.2"
proc-macro2 = "1.0.49"
quote = "1.0.23"
samevariant = { path = "/home/andrew/temp/ren/samevariant" }
syn = "1.0.107"
