[package]
name = "good-ormning"
version = "0.1.1"
edition = "2021"
license = "ISC"
description = "Maybe an ORM"
homepage = "https://github.com/andrewbaxter/good-ormning"
repository = "https://github.com/andrewbaxter/good-ormning"
readme = "readme.md"

[dependencies]
chrono = { version = "0.4.23", optional = true }
enum_dispatch = { version = "0.3.9", optional = true }
genemichaels = { version = "0.1.15", optional = true }
hex = { version = "0.4.3", optional = true }
proc-macro2 = { version = "1.0.49", optional = true }
quote = { version = "1.0.23", optional = true }
rpds = { version = "0.12.0", optional = true }
rusqlite = { version = "0.28.0", optional = true }
samevariant = { version = "0.0.1", optional = true }
syn = { version = "1.0.107", optional = true }
tokio-postgres = { version = "0.7.7", optional = true }

[features]
build = [
    "dep:chrono",
    "dep:enum_dispatch",
    "dep:genemichaels",
    "dep:hex",
    "dep:proc-macro2",
    "dep:quote",
    "dep:rpds",
    "dep:samevariant",
    "dep:syn",
]
run = []
sqlite = ["dep:rusqlite", "run"]
pg = ["dep:tokio-postgres", "run"]

[workspace]
members = ["integration_tests"]
