[package]
name = "goodormning"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
enum_dispatch = "0.3.9"
genemichaels = "0.1.15"
hex = "0.4.3"
proc-macro2 = "1.0.49"
quote = "1.0.23"
samevariant = { path = "/home/andrew/temp/ren/samevariant" }
stable-hash = "0.4.3"
syn = "1.0.107"
