[package]
name = "integration_tests"
version = "0.3.11"
edition = "2021"
publish = false

[dependencies]
chrono = ">=0"
jiff = ">=0"
rusqlite = ">=0"
tokio = { version = ">=0", features = ["macros", "rt"] }
"good-ormning" = { path = "..", features = [
    "chrono",
    "pg",
    "sqlite",
    "jiff",
    "import",
] }
"good-ormning-macros" = { path = "../macros" }
tokio-postgres = { version = ">=0", features = [
    "with-chrono-0_4",
    "with-jiff-0_2",
] }
loga = ">=0"
good-ormning-core = { version = "0.5.11", path = "../core" }
flowcontrol = ">=0"
tempfile = "3.27.0"
pglite-oxide = { git = "https://github.com/f0rr0/pglite-oxide" }

[build-dependencies]
"good-ormning" = { path = "..", features = ["chrono", "jiff", "pg", "sqlite"] }
flowcontrol = ">=0"

[lints.clippy]
all = "allow"
