[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.28.0"
testcontainers = { version = "0.14.0", features = ["tokio"] }
tokio = { version = "1.24.1", features = ["macros", "rt"] }

[build-dependencies]
"good-ormning" = { path = ".." }

[dev-dependencies]
anyhow = "1.0.68"
tokio-postgres = "0.7.7"
