[package]
name = "good-ormning-macros"
version = "0.5.2"
edition = "2021"
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[features]
default = ["pg", "sqlite"]
pg = []
sqlite = []
chrono = ["good-ormning-core/chrono"]
jiff = ["good-ormning-core/jiff"]

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
sqlparser = "0.52"
convert_case = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
good-ormning-core = { version = "0.5.2", path = "../core" }

[lints.clippy]
all = "allow"
